name = "HypertextLiteral"
uuid = "ac1192a8-f4b3-4bfe-ba22-af5b92cd3ab2"
authors = ["Clark C. Evans <cce@clarkevans.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
NarrativeTest = "9563631e-acd4-5dd8-bebb-4cf36518960d"
Hyperscript = "47d2ed2b-36de-50cf-bf87-49c2cf4b8b91"

[targets]
test = ["NarrativeTest", "Hyperscript"]
