name: docs
on:
  push:
    branches: [master]
    tags: [v*]
  pull_request:
jobs:
  Documenter:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-docdeploy@latest
        env:
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
