name: nightly-ci
on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
    workflow_dispatch:
jobs:
    test:
        if: ${{ false }} # disable for now
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                version: ['nightly']
                os: [ubuntu-latest, windows-latest, macOS-latest]
        steps:
            - uses: actions/checkout@v5
            - uses: julia-actions/setup-julia@v1
              with:
                  version: ${{ matrix.version }}
            - uses: julia-actions/julia-buildpkg@v1
            - uses: julia-actions/julia-runtest@v1
            - uses: julia-actions/julia-processcoverage@v1
