name: nightly-ci
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  schedule:
  - cron: "0 9 * * *"
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        version: ['nightly']
        os: [ubuntu-20.04, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
      - uses: julia-actions/julia-buildpkg@master
      - name: Execute Tests for README
        run: julia --color=yes --check-bounds=yes --project -e 'using Pkg; Pkg.test(coverage=true)'
        shell: bash
