name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
#   runs-on: ${{ matrix.os }}
#   strategy:
#     matrix:
#       julia-version: ['1.0', '1.2.0', '^1.3.0']
#       os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.0'
      - name: Execute Tests for README
        run: julia ./test/runtests.jl
        shell: bash
